/*
 * Scream @ https://github.com/michab/dev_smack
 *
 * Copyright © 1998-2022 Michael G. Binz
 */
package de.michab.scream.binding;

import java.lang.reflect.Method;

import de.michab.scream.fcos.Operation;
import de.michab.scream.fcos.Procedure;

/**
 * Represents a default interface that is always added to the list of
 * interfaces generated by the interface factory.
 */
public interface InterfaceConfigurator
{
  /**
   * Defines the operation responsible for handling method calls.  To remove an
   * operation call this with a NIL operation.
   *
   * @param m Calls to this operation on the interface will be forwarded.
   * @param o The receiving operation.
   */
  public Operation defineOperation( Method m, Procedure o );
}
